name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: New
    labels:
      - feat
  - title: Bug Fixes
    labels:
      - fix
  - title: Maintenance
    labels:
      - chore
      - ci
  - title: Documentation
    labels: 
      - docs

change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - breaking
  minor:
    labels:
      - feat
  patch:
    labels:
      - fix
      - chore
      - docs
      - ci
  default: patch
    
exclude-labels:
  - skip-changelog
  - no-release

template: |
  ## What's Changed
  
  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION