name: Publish NuGet Package

on:
  release:
    types: [published]

jobs:
  package-and-publish-lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x

      - name: Generate NuGet Package
        run: |
          dotnet pack src/Deodesy.Library/Deodesy.Library.csproj \
          -c Release \
          -p:PackageVersion=${{ replace(github.event.release.tag_name, 'v', '') }} \
          -p:RepositoryUrl=https://github.com/vitiligo610/Deodesy \
          -o packages

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}